### PR TITLE
Move forms to Form directory

### PR DESCRIPTION
**Pull request by joshirohit100**
Move forms to Form directory. Issue - https://www.drupal.org/node/2548551

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thanks! Some test classes will have to have their namespaces updated as well.

**Comment by joshirohit100** [comment]
@bartfeenstra  - you mean form test classes should also be refactored (as forms) ?

**Comment by bartfeenstra** [comment]
No. By convention our unit test classes mirror the classes they test 1:1, so there's one unit test class per class we test, and the namespaces are also the same, with the exception of a small `Tests` namespace in between. For example, if `\Drupal\currency\Controller\PluginBasedExchangeRateProviderForm` is renamed to `\Drupal\currency\Form\PluginBasedExchangeRateProviderForm`, `\Drupal\Tests\currency\Unit\Controller\PluginBasedExchangeRateProviderFormTest`, must be renamed to `\Drupal\Tests\currency\Unit\Form\PluginBasedExchangeRateProviderFormTest`.

**Comment by bartfeenstra** [comment]
@joshirohit100 Thanks! I patched this directly, so I could give you drupal.org commit credit as well. See https://www.drupal.org/node/2548551.

**Pull request closed without merging**
